name: Send Newsletter

on:
  schedule:
    - cron: "0 8 * * 1-5"  # Run at 9 am UTC (adjust timezone if needed) on Monday to Friday
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  send_newsletter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the Python version required for your script

      - name: Install dependencies
        run: pip install -r requirements.txt  # Replace with the command to install dependencies

      - name: Run newsletter script
        env:
          HUBSPOT_API_BASE_URL: ${{ secrets.HUBSPOT_API_BASE_URL }}
          MAILERSEND_API_KEY: ${{ secrets.MAILERSEND_API_KEY }}
          MAILERSEND_API_EMAIL: ${{ secrets.MAILERSEND_API_EMAIL }}
          HUBSPOT_ACCESS_TOKEN: ${{ secrets.HUBSPOT_ACCESS_TOKEN }}
        run: python send_newsletter.py  # Replace with the command to run your newsletter script
